# Generated by Django 2.1.7 on 2019-07-31 09:12

import datetime
from django.db import migrations, models
import django_cryptography.fields
import django_encrypted_filefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pde', django_cryptography.fields.encrypt(django_encrypted_filefield.fields.EncryptedFileField(upload_to='pde/files/'))),
                ('ip', models.CharField(max_length=16)),
                ('machine', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cat', models.FloatField(blank=True, default=None, null=True)),
                ('exe', models.CharField(max_length=512)),
                ('hash', models.CharField(blank=True, default=None, max_length=256)),
                ('api', models.CharField(blank=True, default='N/A', max_length=256)),
            ],
            options={
                'verbose_name_plural': 'PDE',
            },
        ),
    ]
